<a href="https://colab.research.google.com/github/Shamitha018/Pandas/blob/main/O_15_12_2025_pandas_session_9_missing_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd
import numpy as np
diction1= {'Names': ['Shamitha', 'Lasya', 'Ridhi', np.nan],
           'Age': [np.nan,22,18, 30],
           'City': ['Hyd', 'Nagole', np.nan, 'Pune']
           }
#dictionary to dataframe
d1 = pd.DataFrame(diction1)
d1.to_csv('data1.csv', index = False)

In [38]:
diction2 = {'Names': ['Shamitha', 'Lasya', 'Ridhi', None],
           'Age': [None,22,18, 30],
           'City': ['Hyd', 'Nagole', None, 'Pune']}
d2 = pd.DataFrame(diction2)
d2.to_csv('data2.csv', index = False)

In [39]:
d1

Names   Age    City
0  Shamitha   NaN     Hyd
1     Lasya  22.0  Nagole
2     Ridhi  18.0     NaN
3       NaN  30.0    Pune

In [40]:
d1.isnull()

Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [41]:
d1.isnull().sum() #shows the total number of nulls in dataframe

Names    1
Age      1
City     1
dtype: int64

Difference between NaN and None

for object type we will use None
for number type we will use nan

In [42]:
np.nan

nan

In [43]:
np.nan + 5 #mathematical operations wont fail with nan

nan

In [44]:
None + 5 # mathematical operations will fail when u use none


TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [45]:
arr1 = np.array([1,2,3,np.nan])
arr2 = np.array([1,2,3,None])
arr1

array([ 1.,  2.,  3., nan])

In [46]:
arr2

array([1, 2, 3, None], dtype=object)

In [47]:
arr1.dtype, arr2.dtype

(dtype('float64'), dtype('O'))

In [48]:
np.sum(arr1)

np.float64(nan)

In [49]:
np.sum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [50]:
np.sum(arr1), np.nansum(arr1)

(np.float64(nan), np.float64(6.0))

In [51]:
arr2 #is a object

array([1, 2, 3, None], dtype=object)

converting object type into float type using astype

In [52]:
arr3 = arr2.astype(float)
arr3 #none converted to a nan which is float

array([ 1.,  2.,  3., nan])

In [53]:
arr1

array([ 1.,  2.,  3., nan])

In [54]:
d2['Age'].values.astype(float)

array([nan, 22., 18., 30.])

In [55]:
d2['Age'].values.astype(int)

/tmp/ipython-input-3751503362.py:1: RuntimeWarning: invalid value encountered in cast
  d2['Age'].values.astype(int)


array([-9223372036854775808,                   22,                   18,
                         30])

Filling NaN with random values

In [56]:
d1.fillna(30)

Names   Age    City
0  Shamitha  30.0     Hyd
1     Lasya  22.0  Nagole
2     Ridhi  18.0      30
3        30  30.0    Pune

In [57]:
d1 #data is not overridden so we tried inplace = true to change nan to 30 permanentntaly

Names   Age    City
0  Shamitha   NaN     Hyd
1     Lasya  22.0  Nagole
2     Ridhi  18.0     NaN
3       NaN  30.0    Pune

In [58]:
d1.fillna(30, inplace = False) #change to true

Names   Age    City
0  Shamitha  30.0     Hyd
1     Lasya  22.0  Nagole
2     Ridhi  18.0      30
3        30  30.0    Pune

In [59]:
d1  # to override data

Names   Age    City
0  Shamitha   NaN     Hyd
1     Lasya  22.0  Nagole
2     Ridhi  18.0     NaN
3       NaN  30.0    Pune

fill w specific value based on column

In [61]:
d1['Age'].fillna(88)
#d1['Age'] = d1['Age'].fillna(66, inplace = true)

0    88.0
1    22.0
2    18.0
3    30.0
Name: Age, dtype: float64